// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '[Your API key]',
    appId: '1:132476325415:web:4e0335539e2a54b2270802',
    messagingSenderId: '132476325415',
    projectId: 'dialogi-18a51',
    authDomain: 'dialogi-18a51.firebaseapp.com',
    storageBucket: 'dialogi-18a51.appspot.com',
    measurementId: 'G-CS6SGKDDN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '[Your API key]',
    appId: '1:132476325415:android:76d839159bd207e6270802',
    messagingSenderId: '132476325415',
    projectId: 'dialogi-18a51',
    storageBucket: 'dialogi-18a51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '[Your API key]',
    appId: '1:132476325415:ios:6771923b980ec9a9270802',
    messagingSenderId: '132476325415',
    projectId: 'dialogi-18a51',
    storageBucket: 'dialogi-18a51.appspot.com',
    androidClientId: '132476325415-lrv7jmvp6fjrmcaj60dlc8ol6p30fsbb.apps.googleusercontent.com',
    iosClientId: '132476325415-uknldqs6p0hl4gvl3l5qdfopentre17f.apps.googleusercontent.com',
    iosBundleId: 'com.example.clubhouse',
  );
}
